---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tweeter
  name: mongo-pv-claim
  labels:
    app: tweeter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweeter
  name: mongo
  labels:
    app: tweeter
    tier: db
    service: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tweeter
        tier: db
        service: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: tweeter
  name: mongo
  labels:
    app: tweeter
    tier: db
spec:
  selector:
    app: tweeter
    tier: db
    service: mongo
  ports:
    - port: 27017
